"""Initial schema (Phase 6B).

Captures every table the metadata-only pipeline relied on through
Phases 1 – 6A:

- ``jobs`` — Phase 1 row + Phase 3C voice fields + Phase 3E face fields
  + Phase 4F-2 ``provider_selection`` JSON column.
- ``compliance_events`` — Phase 1 policy gate audit + Phase 3E ``extra``.
- ``stage_runs`` — Phase 2 DAG runner row + Phase 3+ artifacts JSON.
- ``artifacts`` — Phase 3D first-class artifact table + Phase 3E
  ``width``/``height`` + Phase 4A-2 nullable ``job_id``.

Before Phase 6B the runtime relied on ``Base.metadata.create_all()`` in
``app.core.db.init_db``. That path still works for tests (SQLite
in-memory, fresh every run). Real deployments now run
``alembic upgrade head`` instead (see ``make db-upgrade``).

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-15
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending_compliance', 'accepted', 'published', 'rejected', 'failed', name='job_status'), nullable=False),
    sa.Column('brief', sa.String(length=2000), nullable=False),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('synthetic_person_confirmed', sa.Boolean(), nullable=False),
    sa.Column('consent_confirmed', sa.Boolean(), nullable=False),
    sa.Column('watermark_required', sa.Boolean(), nullable=False),
    sa.Column('c2pa_required', sa.Boolean(), nullable=False),
    sa.Column('voice_mode', sa.String(length=32), nullable=False),
    sa.Column('script_text', sa.String(length=8000), nullable=True),
    sa.Column('tts_backend', sa.String(length=32), nullable=False),
    sa.Column('audio_ref', sa.JSON(), nullable=True),
    sa.Column('face_mode', sa.String(length=32), nullable=True),
    sa.Column('image_ref', sa.JSON(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('provider_selection', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('gate', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.Enum('accept', 'reject', name='compliance_decision'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_events_job_id'), ['job_id'], unique=False)

    op.create_table('stage_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'rejected', 'skipped', name='stage_status'), nullable=False),
    sa.Column('noop', sa.Boolean(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stage_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_runs_job_id'), ['job_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('stage_run_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('uri', sa.String(length=2000), nullable=False),
    sa.Column('local_path', sa.String(length=2000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_run_id'], ['stage_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_artifact_type'), ['artifact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifacts_stage_run_id'), ['stage_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifacts_stage_run_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_job_id'))
        batch_op.drop_index(batch_op.f('ix_artifacts_checksum_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifacts_artifact_type'))

    op.drop_table('artifacts')
    with op.batch_alter_table('stage_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stage_runs_job_id'))

    op.drop_table('stage_runs')
    with op.batch_alter_table('compliance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_events_job_id'))

    op.drop_table('compliance_events')
    op.drop_table('jobs')
    # ### end Alembic commands ###
